<?php
/**
 * @file
 * install hooks for custom node types.
 */

/**
 * Implements hook_node_info().
 */
function productcustomtype_node_info() {
  return array(
    'product' => array(
      'name' => t('Product'),
      // Here 'base' key is very important. This key is used to define node type specific hooks. e.g project_form
      'base' => 'product',
      'description' => t('You can define new Products here.'),
      'has_title' => TRUE,
      'title_label' => t('Product title')
      )
    );
}

/**
 * Implement hook_form().
 */
function product_form($node, $form_state) {
  return node_content_form($node, $form_state);
}
